In [23]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/kernel-methods-ammi-2020/Ytr.csv
/kaggle/input/kernel-methods-ammi-2020/Xte.csv
/kaggle/input/kernel-methods-ammi-2020/Xte_mat100.csv
/kaggle/input/kernel-methods-ammi-2020/Xtr_mat100.csv
/kaggle/input/kernel-methods-ammi-2020/Xtr.csv

In [24]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [25]:
X_train=pd.read_csv('/kaggle/input/kernel-methods-ammi-2020/Xtr.csv', sep=',') #we use this dataset to train our model
Y_train=pd.read_csv('/kaggle/input/kernel-methods-ammi-2020/Ytr.csv', sep=',') #we use this dataset to train our model
X_test=pd.read_csv('/kaggle/input/kernel-methods-ammi-2020/Xte.csv', sep=',') #we will use this data set later to validate our model

In [26]:
X_train.tail()

        Id                                                seq
1995  1995  TAACTTTTGACAGGTCAGAATACAAAACTGATTTATTTACAGTGTC...
1996  1996  ACGCCCATTCCGCCCTGCTAAGCCTCGCCCATTACATCCAGACTGC...
1997  1997  TGGCTACTAGCTAGAGATAGCATCTCTCTGTGGACAACTCTCCAGC...
1998  1998  CCCAGCTGTCAAAAAGCAGCCCAAAGGAAGCTCACGGTGTGCCGGC...
1999  1999  TGCTAGTTGATGAAACAATAACTGCTAAAAGGTATACAGCCATGTC...

In [5]:
print('The shape of the X_train dataset is:',X_train.shape)
print('The shape of the Y_train dataset is:',Y_train.shape)

The shape of the X_train dataset is: (2000, 2)
The shape of the Y_train dataset is: (2000, 2)

In [6]:
# X_train['len'] = X_train.seq.apply(lambda x : len(x))

In [27]:
X_train.head()

   Id                                                seq
0   0  GAGGGGCTGGGGAGGGGGCTGGCCCAGAGGCACCAGACTCTGCAGA...
1   1  CGGCCTGGGGGCCACATGTGAGTGCTTACCTGTGTGGGGATGAGGG...
2   2  GACAACGCCGCTGTCAGCCGCCTTCGACTCACCTGGGAGGTGATGA...
3   3  GCCTCCCTTGGCACCACGGGAGACCAGTTTTGGAGGGGCGGGGCTG...
4   4  GCACTACTACACCCATTGCTGTAATAGTAAGTGCCGGTGCCTTCAC...

In [28]:
import string
Alphabet_dict = dict(zip(string.ascii_uppercase, range(1,27)))

In [29]:
#  X_train['seq_1'] = X_train.seq.apply(lambda x : (' '.join(map(str, list(x))))[0])
for i in range(101):
    X_train['seq_'+str(i)] = X_train.seq.apply(lambda x :Alphabet_dict[x[i]])
    X_test['seq_'+str(i)] = X_test.seq.apply(lambda x :Alphabet_dict[x[i]])
#     X_train['seq_'+str(i)] = X_train.seq.apply(lambda x : (' '.join(map(str, list(x))))[i])
    
# X_train['seq_101'] = X_train.seq.apply(lambda x : (' '.join(map(str, list(x))))[101])

In [30]:
X_train.head()

,Id,seq,seq_0,seq_1,seq_2,seq_3,seq_4,seq_5,seq_6,seq_7,...,seq_91,seq_92,seq_93,seq_94,seq_95,seq_96,seq_97,seq_98,seq_99,seq_100
0,0,GAGGGGCTGGGGAGGGGGCTGGCCCAGAGGCACCAGACTCTGCAGA...,7,1,7,7,7,7,3,20,...,3,20,7,7,20,7,7,3,1,7
1,1,CGGCCTGGGGGCCACATGTGAGTGCTTACCTGTGTGGGGATGAGGG...,3,7,7,3,3,20,7,7,...,7,20,3,3,1,7,7,20,7,7
2,2,GACAACGCCGCTGTCAGCCGCCTTCGACTCACCTGGGAGGTGATGA...,7,1,3,1,1,3,7,3,...,3,7,1,1,7,20,7,3,7,20
3,3,GCCTCCCTTGGCACCACGGGAGACCAGTTTTGGAGGGGCGGGGCTG...,7,3,3,20,3,3,3,20,...,7,1,7,20,7,3,20,1,1,1
4,4,GCACTACTACACCCATTGCTGTAATAGTAAGTGCCGGTGCCTTCAC...,7,3,1,3,20,1,3,20,...,1,3,20,7,20,20,1,3,3,3

In [11]:
X = X_train.drop(['seq', 'Id'], axis=1)
X_t = X_test.drop(['seq', 'Id'], axis=1)

In [12]:
y = Y_train.Bound

In [13]:
# X_t

In [31]:
from sklearn.preprocessing import LabelEncoder
import category_encoders as ce

In [32]:
encod = LabelEncoder()

count_enc = ce.CountEncoder()

In [33]:
encod.fit(X_train.seq)

LabelEncoder()

In [17]:
X_train.describe()

,Id,seq_0,seq_1,seq_2,seq_3,seq_4,seq_5,seq_6,seq_7,seq_8,...,seq_91,seq_92,seq_93,seq_94,seq_95,seq_96,seq_97,seq_98,seq_99,seq_100
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,999.500000,7.664500,7.569500,8.034000,7.568000,7.862500,7.633500,7.320500,7.815000,7.546000,...,7.936500,7.63550,7.532500,7.356500,7.766500,7.608000,7.676000,7.368500,7.393000,7.611500
std,577.494589,7.246737,7.254273,7.465635,7.136164,7.282315,7.232035,7.020999,7.290429,7.087736,...,7.368081,7.18237,7.135713,6.994417,7.290786,7.120793,7.147557,7.114142,7.196419,7.272139
min,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,499.750000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,3.000000,3.00000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
50%,999.500000,7.000000,3.000000,7.000000,7.000000,7.000000,5.000000,3.000000,7.000000,7.000000,...,7.000000,7.00000,7.000000,3.000000,7.000000,7.000000,7.000000,3.000000,3.000000,3.000000
75%,1499.250000,7.000000,7.000000,20.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,...,20.000000,7.00000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
max,1999.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,...,20.000000,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000

In [18]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Columns: 103 entries, Id to seq_100
dtypes: int64(102), object(1)
memory usage: 1.6+ MB

In [37]:
class LogisticRegressionBinary():
    def __init__(self, lr=0.1, num_iter=100000, batch_size=1, verbose=False):
        self.lr = lr
        self.num_iter = num_iter
        self.batch_size = batch_size
        self.verbose = verbose
    
    def __add_intercept(self, X):
        intercept = np.ones((X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)
    
    def __sigmoid_func(self, z):
        return 1 / (1 + np.exp(-z))
    
    def __loss(self, h, y):
        return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()
    
    def fit(self, X, y):
        y = self.trans_y(y)
        X = self.__add_intercept(X)
        self.theta = np.zeros(X.shape[1])
        
        for i in range(self.num_iter):
            z = np.dot(X, self.theta)
            h = self.__sigmoid_func(z)
                        
            rand = np.random.choice(y.size, self.batch_size).squeeze()
            gradient = np.dot(X[rand].T, (h[rand] - y[rand]))/y.size   
        
            self.theta -= self.lr * gradient
            #print('theta and grad',self.theta.shape ,  gradient.shape )
            if(self.verbose == True and i % 100 == 0):
                z = np.dot(X, self.theta)
                h = self.__sigmoid(z)
                print(f'loss: {self.__loss(h, y)} \t')
    
    def predict_probability(self, X):
        X = self.__add_intercept(X)
    
        return self.__sigmoid_func(np.dot(X, self.theta))
    
    def predict(self, X, threshold=.5):
          return np.where(self.predict_probability(X) >= 0.5, 1, 0)
        
          
    def Accuracy_check(self,X,y):
        return np.mean(self.predict(X)==y)
    
    def trans_y(self, y):
        if isinstance(y, pd.Series):
            y = y.values
        if isinstance(y, list):
            y = np.array(y)
        return y

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
# train_size = 0.0
# X_train, X_validation, y_train, y_X_validation = train_test_split(X, y, test_size=1-train_size, random_state=101)

In [40]:
LR = LogisticRegressionBinary()

# LR.fit(X_train, y_train)
LR.fit(X, y)

In [41]:
# LR.Accuracy_check(X_validation, y_X_validation)
LR.Accuracy_check(X, y)

0.631

In [ ]:
y_pred = LR.predict(X_t)

In [36]:
#G = GDA_Calculator().fit(X,y)
#LR.Accuracy_check(X, y)

0.6155

In [ ]:
X = np.arange(1000).reshape(-1, 1)
sample = pd.DataFrame(data=X, columns=['Id'])
sample.head()

In [ ]:
sample['Bound'] = y_pred

In [ ]:
sample.tail()

In [ ]:
sample.to_csv('./baseline.csv', index=False)